// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/Tamrin007/goa-demo/design
// --out=$(GOPATH)/src/github.com/Tamrin007/goa-demo
// --version=v1.1.0-dirty
//
// API "Demo App": Hello Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// HelloHelloPath computes a request path to the hello action of Hello.
func HelloHelloPath(name string) string {
	param0 := name

	return fmt.Sprintf("/hello/%s", param0)
}

// API calls your name
func (c *Client) HelloHello(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewHelloHelloRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewHelloHelloRequest create the request corresponding to the hello action endpoint of the Hello resource.
func (c *Client) NewHelloHelloRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
