// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/Tamrin007/goa-demo/design
// --out=$(GOPATH)/src/github.com/Tamrin007/goa-demo
// --version=v1.1.0-dirty
//
// API "Demo App": Application Media Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import "github.com/goadesign/goa"

// Message from Demo App API (default view)
//
// Identifier: application/vnd.goa.example.hello+json; view=default
type GoaExampleHello struct {
	Msg string `form:"msg" json:"msg" xml:"msg"`
}

// Validate validates the GoaExampleHello media type instance.
func (mt *GoaExampleHello) Validate() (err error) {
	if mt.Msg == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "msg"))
	}
	return
}
